modLoader = "javafml"
loaderVersion = "*"
license = "All rights reserved"
issueTrackerURL = "https://github.com/henkelmax/better-respawn"
[[mods]]
modId = "better_respawn"
version = "${mod_version}"
displayName = "Better Respawn"
updateJSONURL = "https://update.maxhenkel.de/forge/better_respawn"
displayURL = "https://modrepo.de/minecraft/better_respawn"
authors = "Max Henkel"
description = '''This mod adds a mechanic that lets you respawn near your death location'''
[[dependencies.better_respawn]]
modId = "forge"
mandatory = true
versionRange = "${forge_dependency}"
ordering = "NONE"
side = "BOTH"
[[dependencies.better_respawn]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "BOTH"